<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ANHROG" ignored="0" name="Unit Test" tests="5" failures="3" timestamp="23 Aug 2017 04:47:54 GMT" time="0.032" errors="0">
  <testcase name="testMethod1" time="0.0" classname="testclasses.SampleTest">
    <failure type="org.testng.TestNGException" message="
Cannot inject @Test annotated Method [testMethod1] with [class java.lang.String, class java.lang.String].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection">
      <![CDATA[org.testng.TestNGException: 
Cannot inject @Test annotated Method [testMethod1] with [class java.lang.String, class java.lang.String].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod2" time="0.004" classname="testclasses.SampleTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	testMethod2 - Values do not match expected [Hello World] but found [Anil.TestAutomationFramework.SomeClassToTest@14342062]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	testMethod2 - Values do not match expected [Hello World] but found [Anil.TestAutomationFramework.SomeClassToTest@14342062]
	at testclasses.SampleTest.testMethod2(SampleTest.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod3" time="0.001" classname="testclasses.SampleTest"/>
  <testcase name="testmethod4" time="0.001" classname="testclasses.SampleTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	testMethod2 - Values do not match expected [Hello World] but found [Anil.TestAutomationFramework.SomeClassToTest@14342062],
	 expected [3] but found [4],
	expected [10] but found [20]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	testMethod2 - Values do not match expected [Hello World] but found [Anil.TestAutomationFramework.SomeClassToTest@14342062],
	 expected [3] but found [4],
	expected [10] but found [20]
	at testclasses.SampleTest.testmethod4(SampleTest.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testmethod4 -->
  <testcase name="testmethod5" time="0.0" classname="testclasses.SampleTest"/>
</testsuite> <!-- Unit Test -->
